### ISSUE TITLE
Define group Constraints and write to constraints.md

### ISSUE THREAD

**Issue by Khadijaramlawi** [MIT-Emerging-Talent/ET6-foundations-group-01#12]
**Objectives** 

This document outlines the constraints and boundaries of our group project, serving as a guide to ensure our work remains focused and efficient.

**Purpose**

- Define Project Scope: Clarify external, involuntary, and voluntary constraints affecting our work.
- Promote Collaboration: Establish shared understanding and guidelines for team efforts.
- Facilitate Planning: Help prioritize tasks and allocate resources effectively.

**Comment by Djokwa** [comment]
Hello. Would you mind please to add me to assignees list. Thank you in advance.

**Comment by Khadijaramlawi** [comment]
Hi Henry. Sorry for not adding you previously, I tried to add you before but your account didn't appear and I assumed you still have some issues with the repo. 
Now, you're added please let me know if you need anything else.
