### ISSUE TITLE
Define the communication strategy for the group.

### ISSUE THREAD

**Issue by suhrobmuboraksho** [MIT-Emerging-Talent/ET6-foundations-group-01#13]
Description of communication.md File

The _communication.md_ file is a comprehensive template designed to structure and standardize team communication. It includes the following key sections:

**1. Communication Schedule:**
         •A table to outline scheduled discussions, their topics, and the preferred method of communication (e.g., meetings, chats).

**2. Communication Channels:**
	•Defines how frequently each channel (e.g., Issues, Pull Requests, Slack/Discord, Video Calls) will be used and their purposes.
	
**3. Availability:**
	•Availability table for team members, specifying their preferred communication times during the week.
	•A section for daily hours commitment per team member.

**4.Asking for Help:**
	• A clear protocol for escalating issues when stuck:
	• 0–30 minutes: Solve independently.
	• 30–60 minutes: Seek help within the group.
	• 60+ minutes: Tag coaches for guidance.

**Comment by olumide-AI** [comment]
Hello Sukhrob, would you please eplain why this issue was created? I'm having a hard time understanding thanks.

**Comment by suhrobmuboraksho** [comment]
Hi Olumide. I created the issue for learning purposes. The interesting thing about the issue is that you can assign it to a pull request and if pull request is closed the issue is resolved automatically.

![image](https://github.com/user-attachments/assets/25429ff8-8d42-4ad7-99c4-275177101aea)
